### PR TITLE
Updated Installation Guide

### PR DESCRIPTION
**Pull request by dyoungwd**
Updated installation Guide and Installation: Dual Boot 
 - chnage mentions from 28 to 30
 - updated images inline with Silverblue 30

One image however not updated is faw-storage-reclaim.png - not sure if the warning appears in Silverblue 30 as could not get it to appear

### CODE REVIEW

**Comment by sanjabonic** [comment]
Hi, @dyoungwd - thanks for your PR!

Would it be possible for you to rebase it and put in your changes again as a new PR? If this message is unclear, you can reach me at the Silverblue forums via direct message. Cheers!

**Comment by dyoungwd** [comment]
Yeah, no probs. Will do it later tonight when I get in

**Comment by allanday** [comment]
We just landed some changes in the docs which have cut down the installation guide fairly considerably. It'd be good to hear what you think of that, @dyoungwd .

To explain the changes: the main goals for this were to avoid having to maintain a lot of docs (which potentially duplicate the official Fedora documentation) and to avoid encouraging users to do things that might be dangerous or risky. One point here is that manual partitioning and dual boot don't seem to behave very well at the moment.

Given that dual boot and manual partitioning are somewhat risky and a bit technical at the moment, I wonder if we could find a good place to keep this material that isn't part of the recommended workflow? For example, maybe it could go in its own section, or on a wiki somewhere.

**Comment by dyoungwd** [comment]
@allanday I had a quick ook at your changes earlier when you submitted the PR. 

I actually thought it was automatic partitioning that would cause issues as it was basically the standard Fedora installer and would have issues with the var/home.

When I get home will have a look properly as many of the changed I did were mainly cosmetics (ie updating the installation process screenshots etc) and may not be required depending on what has been taken out.

What we did on the Korora Project when reworking the docs was use the github wiki for the development purposes of documentation

**Comment by dyoungwd** [comment]
Closed the PR as I can see a fair bit has been removed. I do have a new image of the SB30 installation ( faw-manual-partition-complete.png ) so will be easier and quicker to just refork and submit rather than rebase.

**Pull request closed without merging**
