### PR TITLE
Add root password reset steps for Silverblue

### PR DESCRIPTION
**Pull request by barnscott**
I've seen a few people ask for help with root password reset on Silverblue on the discourse forum. This solution worked for me, so I thought I'd share it.

Can someone else test these steps? Would be good to get confirmation that these steps are appropriate and "best practice".

### CODE REVIEW

**Comment by barnscott** [comment]
I should not that must of this is heavily plagiarized from another Fedora doc. I assume that is satisfactory, but let me know if otherwise.

https://docs.fedoraproject.org/en-US/quick-docs/reset-root-password/#sect-how-to-reset-the-password-from-emergency-or-single-user-mode

**Comment by vojteskas** [comment]
Thanks for the steps! Just tested them on my machine (with encrypted drive) and they do indeed work for me aswell. On a side note, I think two of the steps could use some clarification:

- Step 4, considering encrypted drive: I think it should be explicitely stated that the `plymouth.enable=0` should be on the next (or another) line, because at the beggining of the step, it is asked to go to the end of the line begining with `linux` or similar, which might be confusing
- Step 8: The command needs to be run as a root (or at least with sudo, I haven't tested that), and I think that should also be explicitely stated

Also, I am not sure if everyone is familiar with using vi/vim, especially as nano replaced it as a default text editor. I don't know which approach is the best, but in my humble opinion there should perhaps be a link to a tutorial of using vi, or at least a comment that any other text editor such as nano can also be used. This is probably nitpicking but I thought I would share my thoughts about it.

**Comment by travier** [comment]
If this is mostly a copy of another doc, could we add a link to that doc instead of copy/pasting the content?
If there are changes needed there to adapt to Silverblue, I think it would be fine to add them there.

**Comment by travier** [comment]
This has been merged with https://github.com/fedora-silverblue/silverblue-docs/pull/171. Thanks

**Pull request closed without merging**
