### PR TITLE
remove dual boot problems

### PR DESCRIPTION
**Pull request by bam80**
dual boot should be fixed hopefully with this PR:
https://github.com/rhinstaller/anaconda/pull/2329

### CODE REVIEW

**Comment by bam80** [comment]
Sorry I seems was too harry to request the doc change.
Actually, that PR solves part of the problem - it will work when first OS doesn't use grub for boot (i.e Windows).
If grub.cfg exists in EFI directory of the first OS - there is still error at install time.
So we can't actually say it's OK now.

**Comment by tpopela** [comment]
@bam80 sorry for getting to you that late, but is this still an issue?

**Comment by bam80** [comment]
> 

> Actually, that PR solves part of the problem - it will work when first OS doesn't use grub for boot (i.e Windows).
> If grub.cfg exists in EFI directory of the first OS - there is still error at install time.

@tpopela so we need to test that case when grub.cfg pre-exists in EFI directory (where another OS installation could left it).
I don't have my setup any more to test it for myself ATM, sorry.

**Comment by travier** [comment]
We're not done yet with dual boot issues so let's keep the text as is for now.

**Comment by bam80** [comment]
It would be good to have all the remaining issues in a single place

**Comment by travier** [comment]
We have most of those tracked in https://github.com/fedora-silverblue/issue-tracker/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+boot

**Pull request closed without merging**
